#ifndef CONTROL_TEST_H
#define CONTROL_TEST_H

#include "controller/controls/IControl.h"

class IMessage;

namespace control::test
{
	class AutoGenerateData : public AControl
	{
	public:
		AutoGenerateData();
		~AutoGenerateData();
		void doFunction(Controller& controller) override;
		bool canUndo() const override;
		void undoFunction(Controller& controller) override;
		ControlType getType() const override;
	};
}

#endif