#define VMA_IMPLEMENTATION
#define VMA_USE_STL_CONTAINERS 1

#define VMA_STATS_STRING_ENABLED 0
#define VMA_RECORDING_ENABLED 0
#define VMA_DEDICATED_ALLOCATION 0
#define VMA_STATIC_VULKAN_FUNCTIONS 0
#define VMA_DYNAMIC_VULKAN_FUNCTIONS 0
#include "VulkanMemoryAllocator/vk_mem_alloc.h"
