#ifndef _DEFAULT_USERLISTS_TEXTS_HPP_
#define _DEFAULT_USERLISTS_TEXTS_HPP_

#include <qobject.h>

#define ALL_FIELD_NAME QObject::tr("All")
#define NA_FIELD_NAME QObject::tr("N.A.")

#define DISCIPLINE_USERLIST_NAME QObject::tr("Discipline")
#define ALARM_FIELD_NAME QObject::tr("Alarm")
#define ARCHITECTURE_FIELD_NAME QObject::tr("Architecture")
#define ASBESTOS_FIELD_NAME QObject::tr("Asbestos")
#define CERIFICATION_FIELD_NAME QObject::tr("Certification")
#define CIVILENGINEERING_FIELD_NAME QObject::tr("Civil engineering")
#define CLADDING_FIELD_NAME QObject::tr("Cladding")
#define DEMOLITION_FIELD_NAME QObject::tr("Demolition")
#define DIAGNOSTIC_FIELD_NAME QObject::tr("Diagnostic")
#define DISMANTLING_FIELD_NAME QObject::tr("Dismantling")
#define DOORSANDOPENINGS_FIELD_NAME QObject::tr("Doors and openings")
#define ELECTRICITY_FIELD_NAME QObject::tr("Electricity")
#define ELEVATOR_FIELD_NAME QObject::tr("Elevator")
#define FIERPROTECTION_FIELD_NAME QObject::tr("Fire protection")
#define FLOORING_FIELD_NAME QObject::tr("Flooring")
#define FRAMEWORK_FIELD_NAME QObject::tr("Framework")
#define FURNITURES_FIELD_NAME QObject::tr("Furnitures")
#define HVAC_FIELD_NAME QObject::tr("HVAC")
#define HEATPRODUCTION_FIELD_NAME QObject::tr("Heat production")
#define INSPECTION_FIELD_NAME QObject::tr("Inspection")
#define INSULATION_FIELD_NAME QObject::tr("Insulation")
#define INVESTIGATION_FIELD_NAME QObject::tr("Investigation")
#define JOINERIES_FIELD_NAME QObject::tr("Joineries")
#define LIFTING_FIELD_NAME QObject::tr("Lifting")
#define MAINTENANCE_FIELD_NAME QObject::tr("Maintenance")
#define MEASUREMENT_FIELD_NAME QObject::tr("Measurement")
#define METALWORK_FIELD_NAME QObject::tr("Metalwork")
#define MISC_FIELD_NAME QObject::tr("Misc.")
#define MODELING_FIELD_NAME QObject::tr("Modeling")
#define PARTITION_FIELD_NAME QObject::tr("Partition")
#define PIPING_FIELD_NAME QObject::tr("Piping")
#define PLUMBING_FIELD_NAME QObject::tr("Plumbing")
#define POWERGENERATION_FIELD_NAME QObject::tr("Power generation")
#define RECYLCLING_FIELD_NAME QObject::tr("Recycling")
#define REFREGERATION_FIELD_NAME QObject::tr("Refrigeration")
#define ROOFING_FIELD_NAME QObject::tr("Roofing")
#define SCAFFOLDS_FIELD_NAME QObject::tr("Scaffolds")
#define SECURITY_FIELD_NAME QObject::tr("Security")
#define SPECIALEQUIPEMENT_FIELD_NAME QObject::tr("Special equipment")
#define SPECIALFUILDS_FIELD_NAME QObject::tr("Special fluids")
#define STORAGE_FIELD_NAME QObject::tr("Storage")
#define SURFACETREATEMENT_FIELD_NAME QObject::tr("Surface treatment")
#define WATERTREATEMENT_FIELD_NAME QObject::tr("Water treatment")

#define PHASE_USERLIST_NAME QObject::tr("Phase")
#define AUDIT_FIELD_NAME QObject::tr("Audit")
#define DIAGNOSTIC_FIELD_NAME QObject::tr("Diagnostic")
#define EXISTING_FIELD_NAME QObject::tr("Existing")
#define PROJECT_FIELD_NAME QObject::tr("Project")
#define CALLFORTENDERS_FIELD_NAME QObject::tr("Call for tenders")
#define TECHNICALSTUDIES_FIELD_NAME QObject::tr("Technical studies")
#define DEMOLITION_FIELD_NAME QObject::tr("Demolition")
#define DISMANTLING_FIELD_NAME QObject::tr("Dismantling")
#define CONSTRUCTION_FIELD_NAME QObject::tr("Construction")
#define RECEPTION_FIELD_NAME QObject::tr("Reception")
#define WARRANTY_FIELD_NAME QObject::tr("Warranty")
#define PRODUCTION_FIELD_NAME QObject::tr("Production")
#define MAINTENANCE_FIELD_NAME QObject::tr("Maintenance")
#define P1_FIELD_NAME QObject::tr("P1")
#define P2_FIELD_NAME QObject::tr("P2")
#define P3_FIELD_NAME QObject::tr("P3")
#define P4_FIELD_NAME QObject::tr("P4")
#define P5_FIELD_NAME QObject::tr("P5")
#define P6_FIELD_NAME QObject::tr("P6")
#define P7_FIELD_NAME QObject::tr("P7")
#define P8_FIELD_NAME QObject::tr("P8")
#define P9_FIELD_NAME QObject::tr("P9")
#define P10_FIELD_NAME QObject::tr("P10")

#define FREQUENCY_USERLIST_NAME QObject::tr("Frequency")
#define VERYLOW_FIELD_NAME QObject::tr("Very low")
#define LOW_FIELD_NAME QObject::tr("Low")
#define MEDIUM_FIELD_NAME QObject::tr("Medium")
#define HIGH_FIELD_NAME QObject::tr("High")
#define VERYHIGH_FIELD_NAME QObject::tr("Very high")

#define LOD_USERLIST_NAME QObject::tr("Level of detail")
#define LOD100_FIELD_NAME QObject::tr("LOD100")
#define LOD200_FIELD_NAME QObject::tr("LOD200")
#define LOD300_FIELD_NAME QObject::tr("LOD300")
#define LOD350_FIELD_NAME QObject::tr("LOD350")
#define LOD400_FIELD_NAME QObject::tr("LOD400")

#define SEVERITY_USERLIST_NAME QObject::tr("Severity")
#define CATASTROPHIC_FIELD_NAME QObject::tr("Catastrophic")
#define MAJOR_FIELD_NAME QObject::tr("Major")
#define MINOR_FIELD_NAME QObject::tr("Minor")
#define NEGLIGIBLE_FIELD_NAME QObject::tr("Negligible")
#define SERIOUS_FIELD_NAME QObject::tr("Serious")

#define MODELINGTYPE_USERLIST_NAME QObject::tr("Modeling types")
#define DRAWING2D_FIELD_NAME QObject::tr("2D drawing")
#define DRAWING3D_FIELD_NAME QObject::tr("3D Solid")
#define BIM_FIELD_NAME QObject::tr("BIM")
#define MESH_FIELD_NAME QObject::tr("Mesh")
#define MODELINPLACE_FIELD_NAME QObject::tr("Model in place")

#define MODELINGACCURACY_USERLIST_NAME QObject::tr("Modeling accuracy")
#define M1_FIELD_NAME QObject::tr("1mm")
#define M2_FIELD_NAME QObject::tr("2mm")
#define M3_FIELD_NAME QObject::tr("3mm")
#define M5_FIELD_NAME QObject::tr("5mm")
#define M10_FIELD_NAME QObject::tr("10mm")
#define M20_FIELD_NAME QObject::tr("20mm")
#define M30_FIELD_NAME QObject::tr("30mm")
#define M50_FIELD_NAME QObject::tr("50mm")

#define STATUS_USERLIST_NAME QObject::tr("Status")
#define TODO_FIELD_NAME QObject::tr("To do")
#define INPROGRESS_FIELD_NAME QObject::tr("In progress")
#define DONE_FIELD_NAME QObject::tr("Done")
#define VALIDATED_FIELD_NAME QObject::tr("Validated")
#define PAUSED_FIELD_NAME QObject::tr("Paused")
#define CANCELLED_FIELD_NAME QObject::tr("Cancelled")

#define RISKS_USERLIST_NAME QObject::tr("Risks")
#define ASPHYXIATION_FILED_NAME QObject::tr("Asphyxiation")
#define BURNSSCALDS_FILED_NAME QObject::tr("Burns - scalds")
#define COLLISION_FILED_NAME QObject::tr("Collision")
#define COMPRESSEDGAZ_FILED_NAME QObject::tr("Compressed gases")
#define CORROSIVE_FILED_NAME QObject::tr("Corrosive")
#define CUTS_FILED_NAME QObject::tr("Cuts")
#define ELECTRICSHOCK_FILED_NAME QObject::tr("Electric shock")
#define ENTRAPEMENT_FILED_NAME QObject::tr("Entrapment")
#define ENVITOXICITY_FILED_NAME QObject::tr("Environ.toxicity")
#define EXPLOSIVE_FILED_NAME QObject::tr("Explosive")
#define EYEINJURY_FILED_NAME QObject::tr("Eye injury")
#define FALLS_FILED_NAME QObject::tr("Falls")
#define FIRE_FILED_NAME QObject::tr("Fire")
#define FLAMMABLE_FILED_NAME QObject::tr("Flammable")
#define IRRITANT_FILED_NAME QObject::tr("Irritant")
#define MUSCULOSKELETALDISORDER_FILED_NAME QObject::tr("Musculoskeletal disorders")
#define NOISE_FILED_NAME QObject::tr("Noise")
#define OBSTRUCTION_FILED_NAME QObject::tr("Obstruction")
#define OCIDIZING_FILED_NAME QObject::tr("Oxidizing")
#define POSTUREHAZARD_FILED_NAME QObject::tr("Posture hazards")
#define RADIATION_FILED_NAME QObject::tr("Radiation")
#define SLIPPERY_FILED_NAME QObject::tr("Slippery")
#define STRUCK_FILED_NAME QObject::tr("Struck")
#define TOXIC_FILED_NAME QObject::tr("Toxic")

#define SECURITYEQUIPEMENT_USERLIST_NAME QObject::tr("Security equipment")
#define AIDPOST_FIELD_NAME QObject::tr("Aid post")
#define ALARM_FIELD_NAME QObject::tr("Alarm")
#define ASSEMBLYPOINT_FIELD_NAME QObject::tr("Assembly point")
#define BREAKER_FIELD_NAME QObject::tr("Breaker")
#define CO2EXTINGUISHER_FIELD_NAME QObject::tr("CO2 extinguisher")
#define CHEMICALEXTINGUISHER_FIELD_NAME QObject::tr("Chemical extinguisher")
#define CONTAINMENTAREA_FIELD_NAME QObject::tr("Containment area")
#define DEFIBRILLATOR_FIELD_NAME QObject::tr("Defibrillator")
#define EMERGENCYEXIT_FIELD_NAME QObject::tr("Emergency exit")
#define EYEWASH_FIELD_NAME QObject::tr("Eye wash")
#define FIREDOOR_FIELD_NAME QObject::tr("Fire door")
#define FIREHOSE_FIELD_NAME QObject::tr("Fire hose")
#define INFIRMARY_FIELD_NAME QObject::tr("Infirmary")
#define PHONE_FIELD_NAME QObject::tr("Phone")
#define SCBA_FIELD_NAME QObject::tr("SCBA")
#define SHOWER_FIELD_NAME QObject::tr("Shower")
#define SMOKEVENT_FIELD_NAME QObject::tr("Smoke vent")
#define SPRINKLER_FIELD_NAME QObject::tr("Sprinkler")
#define STOPPUSHBUTTON_FIELD_NAME QObject::tr("Stop push button")
#define STOPVALVE_FIELD_NAME QObject::tr("Stop valve")
#define WATERSPRAYEXTINGUISHER_FIELD_NAME QObject::tr("Water spray extinguisher")

#define NONCONPLIANTCE_USERLIST_NAME QObject::tr("Non-compliance")
#define ASPERITY_FILED_NAME QObject::tr("Asperity")
#define BADPERFORMANCES_FILED_NAME QObject::tr("Bad performances")
#define BADWELDING_FILED_NAME QObject::tr("Bad welding")
#define BADLYPAINTED_FILED_NAME QObject::tr("Badly painted")
#define BARE_FILED_NAME QObject::tr("Bare")
#define BENT_FILED_NAME QObject::tr("Bent")
#define BREAKDOWN_FILED_NAME QObject::tr("Breakdown")
#define BROKEN_FILED_NAME QObject::tr("Broken")
#define BUMP_FILED_NAME QObject::tr("Bump")
#define BURNT_FILED_NAME QObject::tr("Burnt")
#define CLOGGED_FILED_NAME QObject::tr("Clogged")
#define CLUTTERED_FILED_NAME QObject::tr("Cluttered")
#define COLD_FILED_NAME QObject::tr("Cold")
#define CONDENSATION_FILED_NAME QObject::tr("Condensation")
#define CONTACTFAILURE_FILED_NAME QObject::tr("Contact failure")
#define CRACK_FILED_NAME QObject::tr("Crack")
#define DARK_FILED_NAME QObject::tr("Dark")
#define DIRT_FILED_NAME QObject::tr("Dirt")
#define DISTORTED_FILED_NAME QObject::tr("Distorted")
#define DUSTY_FILED_NAME QObject::tr("Dusty")
#define ERASED_FILED_NAME QObject::tr("Erased")
#define FROZEN_FILED_NAME QObject::tr("Frozen")
#define HOLE_FILED_NAME QObject::tr("Hole")
#define HOLLOW_FILED_NAME QObject::tr("Hollow")
#define HOT_FILED_NAME QObject::tr("Hot")
#define HUMID_FILED_NAME QObject::tr("Humid")
#define INCORRECTASSEMBLY_FILED_NAME QObject::tr("Incorrect assembly")
#define INFILTRATION_FILED_NAME QObject::tr("Infiltration")
#define LEAKAGE_FILED_NAME QObject::tr("Leakage")
#define LEVELTOOHIGH_FILED_NAME QObject::tr("Level too high")
#define LEVELTOOLOW_FILED_NAME QObject::tr("Level too low")
#define LOOSE_FILED_NAME QObject::tr("Loose")
#define LOWLIGHT_FILED_NAME QObject::tr("Low light")
#define LOWPRESSURE_FILED_NAME QObject::tr("Low pressure")
#define MELTED_FILED_NAME QObject::tr("Melted")
#define MISALIGNEMENT_FILED_NAME QObject::tr("Misalignment")
#define MISMATCH_FILED_NAME QObject::tr("Mismatch")
#define MOLD_FILED_NAME QObject::tr("Mold")
#define NOISY_FILED_NAME QObject::tr("Noisy")
#define NOTCALIBRATED_FILED_NAME QObject::tr("Not calibrated")
#define NOTINSULATED_FILED_NAME QObject::tr("Not insulated")
#define NOTLEVELED_FILED_NAME QObject::tr("Not leveled")
#define NOTMARKEDOUT_FILED_NAME QObject::tr("Not marked out")
#define NOTPROTECTED_FILED_NAME QObject::tr("Not protected")
#define OUTOFTOLERANCE_FILED_NAME QObject::tr("Out of tolerance")
#define OUTDATED_FILED_NAME QObject::tr("Outdated")
#define OVERLOADED_FILED_NAME QObject::tr("Overloaded")
#define PEELING_FILED_NAME QObject::tr("Peeling")
#define POORFLOW_FILED_NAME QObject::tr("Poor flow")
#define POORSIGNAGE_FILED_NAME QObject::tr("Poor signage")
#define POORVENTILATION_FILED_NAME QObject::tr("Poor ventilation")
#define PRESSURETOOHIGH_FILED_NAME QObject::tr("Pressure too high")
#define PRESSURETOOLOW_FILED_NAME QObject::tr("Pressure too low")
#define PUDDLE_FILED_NAME QObject::tr("Puddle")
#define RUSTY_FILED_NAME QObject::tr("Rusty")
#define SCRATCH_FILED_NAME QObject::tr("Scratch")
#define SHARP_FILED_NAME QObject::tr("Sharp")
#define SLIPPERY_FILED_NAME QObject::tr("Slippery")
#define SMELL_FILED_NAME QObject::tr("Smell")
#define STAGNANTWATER_FILED_NAME QObject::tr("Stagnant water")
#define STAIN_FILED_NAME QObject::tr("Stain")
#define TORN_FILED_NAME QObject::tr("Torn")
#define UNSCREWED_FILED_NAME QObject::tr("Unscrewed")
#define VIBRATIONS_FILED_NAME QObject::tr("Vibrations")
#define WET_FILED_NAME QObject::tr("Wet")
#define WRONGCOLOR_FILED_NAME QObject::tr("Wrong color")
#define WRONGITEM_FILED_NAME QObject::tr("Wrong item")
#define WRONGLOCATION_FILED_NAME QObject::tr("Wrong location")
#define WRONGSIZE_FILED_NAME QObject::tr("Wrong size")

//StandardLists

#define STANDARDPIPE_NA_NAME L"N.A."
#define STANDARDPIPE_STAINLESS_SMS_EN_10357_NAME L"Stainless SMS EN 10357"
#define STANDARDPIPE_STAINLESS_DIN_11850_NAME L"Stainless DIN 11850"
#define STANDARDPIPE_STEEL_ASME_B36_10_NAME L"Steel ASME B36.10"
#define STANDARDPIPE_STAINLESS_EN_10217_7_NAME L"Stainless  EN 10217-7"
#define STANDARDPIPE_COPPER_EN_1057_NAME L"Copper EN 1057"
#define STANDARDPIPE_PVC_EN_1453_1_NAME L"PVC EN 1453-1"
#define STANDARDPIPE_DUCT_EN_1506_NAME L"Duct EN 1506"
#define STANDARDPIPE_STEEL_EN_10216_NAME L"Steel EN 10216"
#define STANDARDPIPE_STEEL_EN_10219_NAME L"Steel EN 10219"

#endif //! _DEFAULT_USERLISTS_TEXTS_HPP_