#ifndef MAIN_GUI_TEXTS_HPP
#define MAIN_GUI_TEXTS_HPP

#include <QtCore/qobject.h>

#define TEXT_WORKSPACE QObject::tr("Workspace")
#define TEXT_PROPERTIES QObject::tr("Properties")
#define TEXT_TOOLBAR QObject::tr("ToolBar")
#define TEXT_HOME QObject::tr("Home")
#define TEXT_TAG QObject::tr("Tag")
#define TEXT_EXPORT QObject::tr("Export")
#define TEXT_SHARE QObject::tr("Share")
#define TEXT_POINT_CLOUD QObject::tr("Point Cloud")
#define TEXT_MEASURE QObject::tr("Measure")
#define TEXT_EXPERIMENT QObject::tr("Experiment")
#define TEXT_MEASURE_DISPLAY QObject::tr("Display")
#define TEXT_ANALYSIS QObject::tr("Analysis")
#define TEXT_RAMPS QObject::tr("Ramps")
#define TEXT_MODEL QObject::tr("Model")
#define TEXT_STRUCTURE_ANALYSIS QObject::tr("Structural Analysis")
#define TEXT_AUTO_SOWING QObject::tr("Experimental - Auto Sowing")
#define TEXT_PIPES QObject::tr("Pipes")
#define TEXT_TAB_SPHERES QObject::tr("Spheres")
#define TEXT_CONNECTION QObject::tr("Connection")
#define TEXT_SLAB QObject::tr("Auto-extended box")
#define TEXT_OTHER QObject::tr("Other")
#define TEXT_MESHOBJECT QObject::tr("External Model")
#define TEXT_SCANTRA QObject::tr("Scantra registration")
#define TEXT_BEAM_DETECTION QObject::tr("Beam Detection")
#define TEXT_VIEW QObject::tr("View")
#define TEXT_CLIPPING QObject::tr("Clipping")
#define TEXT_POINT_CLOUD_OBJECT QObject::tr("Point Cloud Object")
#define TEXT_IMPORT QObject::tr("Import")
#define TEXT_PROJECT QObject::tr("Project")
#define TEXT_VIEWPOINT QObject::tr("Viewpoint")
#define TEXT_MANAGE QObject::tr("Manage")
#define TEXT_ATTRIBUTE QObject::tr("Attribute")
#define TEXT_FILTER QObject::tr("Search")
#define TEXT_FIND_SCAN QObject::tr("Find Scan")
#define TEXT_LISTS QObject::tr("Lists")
#define TEXT_IMAGE QObject::tr("Image")
#define TEXT_VIDEO QObject::tr("Video")
#define TEXT_ANIMATION QObject::tr("Animation")
#define TEXT_VIEWING_MODE QObject::tr("Viewing mode")
#define TEXT_ORIENTATIONS QObject::tr("Orientation")
#define TEXT_MANIPULATE QObject::tr("Manipulate")
#define TEXT_ALIGN_VIEW QObject::tr("Align view")
#define TEXT_NAVIGATE QObject::tr("Navigate")
#define TEXT_SHOW_HIDE QObject::tr("Show / Hide")
#define TEXT_BOX QObject::tr("Box")
#define TEXT_PIPING QObject::tr("Piping")
#define TEXT_POINT_EDITION QObject::tr("Point Edition")
#define TEXT_OPEN_PROJECT QObject::tr("Open Project")
#define TEXT_IMPORT_SCANS QObject::tr("Import Scans")
#define TEXT_ALL QObject::tr("All users")
#define TEXT_ALL_TEMPLATE QObject::tr("All templates")
#define TEXT_TEXT_DISPLAY QObject::tr("Text Display")
#define TEXT_MARKER_DISPLAY_OPTIONS QObject::tr("Marker Display Options")
#define TEXT_CLIPPING_GROUP_NAME QObject::tr("Objects clipping")
#define TEXT_NORMALS_OPTIONS QObject::tr("Normals")
#define TEXT_ORTHO_GRID QObject::tr("Ortho Grid")
#define TEXT_TAB_TRANSPARENCY QObject::tr("Transparency")

#endif