#ifndef MARKER_TEXTS_HPP
#define MARKER_TEXTS_HPP

#include <QObject>

//MarkerDefinitions
#define TEXT_MARKER_DEFINITION_SURVEY_EQUIPEMENT QObject::tr("Survey Equipment")
#define TEXT_MARKER_DEFINITION_TARGET QObject::tr("Target")
#define TEXT_MARKER_DEFINITION_BEAMBENDING QObject::tr("BeamBending")
#define TEXT_MARKER_DEFINITION_POINT QObject::tr("Point")
#define TEXT_MARKER_DEFINITION_VIEWPOINT QObject::tr("ViewPoint")
#define TEXT_MARKER_DEFINITION_COLUMNTILT QObject::tr("Target")
#define TEXT_MARKER_DEFINITION_BASIC_TAG QObject::tr("Basic Tag")
#define TEXT_MARKER_DEFINITION_VIGILANCE QObject::tr("Vigilance")
#define TEXT_MARKER_DEFINITION_CONE QObject::tr("Cone")
#define TEXT_MARKER_DEFINITION_DELETE QObject::tr("Delete")
#define TEXT_MARKER_DEFINITION_DROP QObject::tr("Drop")
#define TEXT_MARKER_DEFINITION_FLAG QObject::tr("Flag")
#define TEXT_MARKER_DEFINITION_INFORMATION QObject::tr("Information")
#define TEXT_MARKER_DEFINITION_INSTRUMENTATION QObject::tr("Instrumentation")
#define TEXT_MARKER_DEFINITION_RECYCLE QObject::tr("Recycle")
#define TEXT_MARKER_DEFINITION_REPAIR QObject::tr("Repair")
#define TEXT_MARKER_DEFINITION_TICK QObject::tr("Tick")
#define TEXT_MARKER_DEFINITION_TRASHCAN QObject::tr("Trashcan")
#define TEXT_MARKER_DEFINITION_EXPLOSIVE_ATMOSPHERE QObject::tr("Explosive Atmosphere")
#define TEXT_MARKER_DEFINITION_RISK_OF_FAILING QObject::tr("Risk of falling")
#define TEXT_MARKER_DEFINITION_ELECTRICITY QObject::tr("Electricity")
#define TEXT_MARKER_DEFINITION_LASER QObject::tr("Laser")
#define TEXT_MARKER_DEFINITION_RADIATIONS QObject::tr("Radiations")
#define TEXT_MARKER_DEFINITION_HOT_SURFACE QObject::tr("Hot Surface")
#define TEXT_MARKER_DEFINITION_FALLING_OBJECTS QObject::tr("Falling Objects")
#define TEXT_MARKER_DEFINITION_CAMERA QObject::tr("Camera")
#define TEXT_MARKER_DEFINITION_FORKLIFT QObject::tr("Forklift")
#define TEXT_MARKER_DEFINITION_WARNING QObject::tr("Warning")
#define TEXT_MARKER_DEFINITION_OXIDIZE QObject::tr("Oxidizer")
#define TEXT_MARKER_DEFINITION_FLAMMABLE QObject::tr("Flammable")
#define TEXT_MARKER_DEFINITION_EXPLOSIVE QObject::tr("Explosive")
#define TEXT_MARKER_DEFINITION_TOXIC QObject::tr("Toxic")
#define TEXT_MARKER_DEFINITION_PRESSURE_EQUIPEMENT QObject::tr("Pressure Equipment")
#define TEXT_MARKER_DEFINITION_CARCINOGEN QObject::tr("Carcinogen")
#define TEXT_MARKER_DEFINITION_ENVIRONMENT QObject::tr("Environment")
#define TEXT_MARKER_DEFINITION_BREATHING_APPARATUS QObject::tr("Breathing Apparatus")
#define TEXT_MARKER_DEFINITION_SAFETY_HELMET QObject::tr("Safety Helmet")
#define TEXT_MARKER_DEFINITION_SAFETY_SHOES QObject::tr("Safety Shoes")
#define TEXT_MARKER_DEFINITION_FILTER QObject::tr("Filter")
#define TEXT_MARKER_DEFINITION_SAFETY_GLOVES QObject::tr("Safety Gloves")
#define TEXT_MARKER_DEFINITION_HARNESS QObject::tr("Harness")
#define TEXT_MARKER_DEFINITION_SAFETY_GLASSES QObject::tr("Safety Glasses")
#define TEXT_MARKER_DEFINITION_MASK QObject::tr("Mask")
#define TEXT_MARKER_DEFINITION_EAR_PROTECTION QObject::tr("Ear Protection")
#define TEXT_MARKER_DEFINITION_WORK_CLOTHES QObject::tr("Work Clothes")
#define TEXT_MARKER_DEFINITION_OVERSHOES QObject::tr("Overshoes")
#define TEXT_MARKER_DEFINITION_HYGIENE_CAP QObject::tr("Hygiene Cap")
#define TEXT_MARKER_DEFINITION_STOP QObject::tr("Stop")
#define TEXT_MARKER_DEFINITION_DEFIBRILLATOR QObject::tr("Defibrillator")
#define TEXT_MARKER_DEFINITION_SHOWER QObject::tr("Shower")
#define TEXT_MARKER_DEFINITION_MEETING_POINT QObject::tr("Meeting Point")
#define TEXT_MARKER_DEFINITION_EYE_WASH QObject::tr("Eye Wash")
#define TEXT_MARKER_DEFINITION_INFIRMARY QObject::tr("Infirmary")
#define TEXT_MARKER_DEFINITION_EMERGENCY_EXIT QObject::tr("Emergency Exit")
#define TEXT_MARKER_DEFINITION_EMERGENCY_PHONE QObject::tr("Emergency Phone")
#define TEXT_MARKER_DEFINITION_ALARM QObject::tr("Alarm")
#define TEXT_MARKER_DEFINITION_FIRE_EXTINGUISHER QObject::tr("Fire Extinguisher")
#define TEXT_MARKER_DEFINITION_FIRE_HOSE QObject::tr("Fire Hose")
#define TEXT_MARKER_DEFINITION_FIRE_PHONE QObject::tr("Fire Phone")

#endif