#include "controller/controls/ControlTest.h"
#include "controller/Controller.h"
#include "controller/functionSystem/FunctionManager.h"

namespace control::test
{
	/*
	** AutoGenerateData
	*/

	AutoGenerateData::AutoGenerateData()
	{
	}

	AutoGenerateData::~AutoGenerateData()
	{
	}

	void AutoGenerateData::doFunction(Controller& controller)
	{
		controller.getFunctionManager().launchFunction(controller, ContextType::autoGenerateData);
	}

	bool AutoGenerateData::canUndo() const
	{
		return (false);
	}

	void AutoGenerateData::undoFunction(Controller& controller)
	{
	}

	ControlType AutoGenerateData::getType() const
	{
		return (ControlType::test_autoGenerateData);
	}

}